name: "Build Shared Library Binaries"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        build:
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            filename: "zatnat.dll"
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
            filename: "libzatnat.so"
          - os: "macos-latest"
            target: "aarch64-apple-darwin"
            filename: "libzatnat.dylib"
          # うるせ～！知らね～！
          # - os: "macos-latest"
          #   target: "x86_64-apple-darwin"

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          target: ${{ matrix.build.target }}
      - uses: "Swatinem/rust-cache@v2"

      - run: "cargo build --release --target=${{ matrix.build.target }}"

      - uses: actions/upload-artifact@v4
        with:
          name: "Shared Library"
          path: "./target/${{ matrix.build.target }}/release/${{ matrix.build.filename }}"
