name: "Check Rust Codes"

on:
  - "pull_request"

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          components: "rustfmt, clippy"
      - uses: "Swatinem/rust-cache@v2"

      - run: "cargo test --all-features"

  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          components: "rustfmt, clippy"
      - uses: "Swatinem/rust-cache@v2"

      - uses: "actions-rust-lang/rustfmt@v1"
      - run: "cargo clippy --all-features"
